name: ci-run-docs

on:
  push:
    branches: [ main ]
    tags:     [ "v*.*.*" ]
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yaml'
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch, tag or commit to deploy the docs. If empty, use the ref that triggered the workflow."
        required: false
        default: ""
      version:
        type: string
        description: "Version of the documentation to deploy"
        required: false
        default: "latest"

permissions:
  contents: write
  pages:    write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  DOCS_ROOT: docs
  DOCS_SRC:  docs/src
  ENABLE_TESTS: false

jobs:
  deploy-docs:
    name: deploy-docs 📘
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref || '' }}

    - name: Extract version from tag
      if: startsWith(github.ref, 'refs/tags/')
      id: version
      shell: bash -e {0}
      run: |
        echo "value=${GITHUB_REF_NAME#*-}" >> "$GITHUB_OUTPUT"

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable

    - name: Install deps
      run: forge install

    - name: Forge → markdown
      run: forge doc --out doc-temp

    - name: Replace contracts/ subtree in docs/src
      shell: bash -e {0}
      run: |
        rm -rf $DOCS_SRC/contracts
        mkdir -p  $DOCS_SRC
        rsync -a --delete doc-temp/src/contracts $DOCS_SRC/
        rm -rf doc-temp

    - name: Deploy mdBook to gh-pages
      uses: matter-labs/deploy-mdbooks@c72ae3825faeb7d20cbf3e67714f7253dd0ee7cb
      with: 
        version:      ${{ inputs.version || steps.version.outputs.value || github.ref_name }}
        docs-dir:     ${{ env.DOCS_ROOT }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        enable-tests: ${{ env.ENABLE_TESTS }}
        deploy:       ${{ github.event_name != 'pull_request' }}
