name: Release-please

# Give permissions to the release-please bot to open and update PRs
# and commit to PRs the repository to update package.json
permissions:
  contents: write
  pull-requests: write
  id-token: write
  attestations: write
  packages: write

# Run the workflow on push to the main branch and manually
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  # Prepare the release PR with changelog updates and create github releases
  # Do not publish to crates.io or upgrade dependencies
  release-please:
    uses: matter-labs/zksync-ci-common/.github/workflows/release-please.yaml@v1
    secrets:
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
      gh_token: ${{ secrets.RELEASE_TOKEN }}
    with:
      config: '.github/release-please/config.json'     # Specify the path to the configuration file
      manifest: '.github/release-please/manifest.json' # Specify the path to the manifest file
      upgrade-dependencies: false                      # Do not upgrade workspace dependencies

  # Trigger workflow to publish binaries
  release-binaries:
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    needs: release-please
    uses: ./.github/workflows/ci-release.yaml
    with:
      tag: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit
